const mockDatabase = {
  trips: [
    {
      name: 'Поездка 1',
      location: 'Екатеринбург',
      cargo: ['Стройматериалы'],
      price: 750,
      image: 'http://via.placeholder.com/200x150',
    },
    {
      name: 'Поездка 2',
      location: 'Самара',
      cargo: ['Люди'],
      price: 1400,
      image: 'http://via.placeholder.com/300x300',
    },
    {
      name: 'Поездка 3',
      location: 'Москва',
      cargo: ['Навоз'],
      price: 3500,
      image: 'http://via.placeholder.com/300x100',
    },
    {
      name: 'Поездка 4',
      location: 'Саратов',
      cargo: ['Микротранзисторы'],
      price: 1700,
      image: 'http://via.placeholder.com/100x300',
    },
    {
      name: 'Поездка 5',
      location: 'Киров',
      cargo: ['Люди', 'Навоз'],
      price: 600,
      image: 'http://via.placeholder.com/200x200',
    },
    {
      name: 'Поездка 6',
      location: 'Вологда',
      cargo: ['Масло'],
      price: 3200,
      image: 'http://via.placeholder.com/140x80',
    },
    {
      name: 'Поездка 7',
      location: 'Питер',
      cargo: [
        'Статуэтки',
        'Картины',
        'Бухлишко',
        'Вазы',
        'Стразы',
        'Перо павлина',
      ],
      price: 3200,
      image: 'http://via.placeholder.com/140x80',
    },
    {
      name: 'Поездка 8',
      location: 'Владивосток',
      cargo: ['Икра'],
      price: 12400,
      image: 'http://via.placeholder.com/200x300',
    },
    {
      name: 'Поездка 9',
      location: 'Якутск',
      cargo: ['Шубы', 'Алмазы'],
      price: 9500,
      image: 'http://via.placeholder.com/300x300',
    },
    {
      name: 'Поездка 10',
      location: 'Африка',
      cargo: ['Бананы', 'Дикие обезьяны'],
      price: 42400,
      image: 'http://via.placeholder.com/100x100',
    },
    {
      name: 'Поездка 11',
      location: 'Екатеринбург',
      cargo: ['Стройматериалы'],
      price: 750,
      image: 'http://via.placeholder.com/200x150',
    },
    {
      name: 'Поездка 12',
      location: 'Самара',
      cargo: ['Люди'],
      price: 1400,
      image: 'http://via.placeholder.com/300x300',
    },
    {
      name: 'Поездка 13',
      location: 'Москва',
      cargo: ['Навоз'],
      price: 3500,
      image: 'http://via.placeholder.com/300x100',
    },
    {
      name: 'Поездка 14',
      location: 'Саратов',
      cargo: ['Микротранзисторы'],
      price: 1700,
      image: 'http://via.placeholder.com/100x300',
    },
    {
      name: 'Поездка 15',
      location: 'Киров',
      cargo: ['Люди', 'Навоз'],
      price: 600,
      image: 'http://via.placeholder.com/200x200',
    },
    {
      name: 'Поездка 16',
      location: 'Вологда',
      cargo: ['Масло'],
      price: 3200,
      image: 'http://via.placeholder.com/140x80',
    },
    {
      name: 'Поездка 17',
      location: 'Питер',
      cargo: [
        'Статуэтки',
        'Картины',
        'Бухлишко',
        'Вазы',
        'Стразы',
        'Перо павлина',
      ],
      price: 3200,
      image: 'http://via.placeholder.com/140x80',
    },
    {
      name: 'Поездка 18',
      location: 'Владивосток',
      cargo: ['Икра'],
      price: 12400,
      image: 'http://via.placeholder.com/200x300',
    },
    {
      name: 'Поездка 19',
      location: 'Якутск',
      cargo: ['Шубы', 'Алмазы'],
      price: 9500,
      image: 'http://via.placeholder.com/300x300',
    },
    {
      name: 'Поездка 20',
      location: 'Африка',
      cargo: ['Бананы', 'Дикие обезьяны'],
      price: 42400,
      image: 'http://via.placeholder.com/100x100',
    },
    {
      name: 'Поездка 21',
      location: 'Екатеринбург',
      cargo: ['Стройматериалы'],
      price: 750,
      image: 'http://via.placeholder.com/200x150',
    },
    {
      name: 'Поездка 22',
      location: 'Самара',
      cargo: ['Люди'],
      price: 1400,
      image: 'http://via.placeholder.com/300x300',
    },
    {
      name: 'Поездка 23',
      location: 'Москва',
      cargo: ['Навоз'],
      price: 3500,
      image: 'http://via.placeholder.com/300x100',
    },
    {
      name: 'Поездка 24',
      location: 'Саратов',
      cargo: ['Микротранзисторы'],
      price: 1700,
      image: 'http://via.placeholder.com/100x300',
    },
    {
      name: 'Поездка 25',
      location: 'Киров',
      cargo: ['Люди', 'Навоз'],
      price: 600,
      image: 'http://via.placeholder.com/200x200',
    },
    {
      name: 'Поездка 26',
      location: 'Вологда',
      cargo: ['Масло'],
      price: 3200,
      image: 'http://via.placeholder.com/140x80',
    },
    {
      name: 'Поездка 27',
      location: 'Питер',
      cargo: [
        'Статуэтки',
        'Картины',
        'Бухлишко',
        'Вазы',
        'Стразы',
        'Перо павлина',
      ],
      price: 3200,
      image: 'http://via.placeholder.com/140x80',
    },
    {
      name: 'Поездка 28',
      location: 'Владивосток',
      cargo: ['Икра'],
      price: 12400,
      image: 'http://via.placeholder.com/200x300',
    },
    {
      name: 'Поездка 29',
      location: 'Якутск',
      cargo: ['Шубы', 'Алмазы'],
      price: 9500,
      image: 'http://via.placeholder.com/300x300',
    },
    {
      name: 'Поездка 30',
      location: 'Африка',
      cargo: ['Бананы', 'Дикие обезьяны'],
      price: 42400,
      image: 'http://via.placeholder.com/100x100',
    },
    {
      name: 'Поездка 31',
      location: 'Екатеринбург',
      cargo: ['Стройматериалы'],
      price: 750,
      image: 'http://via.placeholder.com/200x150',
    },
    {
      name: 'Поездка 32',
      location: 'Самара',
      cargo: ['Люди'],
      price: 1400,
      image: 'http://via.placeholder.com/300x300',
    },
    {
      name: 'Поездка 33',
      location: 'Москва',
      cargo: ['Навоз'],
      price: 3500,
      image: 'http://via.placeholder.com/300x100',
    },
    {
      name: 'Поездка 34',
      location: 'Саратов',
      cargo: ['Микротранзисторы'],
      price: 1700,
      image: 'http://via.placeholder.com/100x300',
    },
    {
      name: 'Поездка 35',
      location: 'Киров',
      cargo: ['Люди', 'Навоз'],
      price: 600,
      image: 'http://via.placeholder.com/200x200',
    },
    {
      name: 'Поездка 36',
      location: 'Вологда',
      cargo: ['Масло'],
      price: 3200,
      image: 'http://via.placeholder.com/140x80',
    },
    {
      name: 'Поездка 37',
      location: 'Питер',
      cargo: [
        'Статуэтки',
        'Картины',
        'Бухлишко',
        'Вазы',
        'Стразы',
        'Перо павлина',
      ],
      price: 3200,
      image: 'http://via.placeholder.com/140x80',
    },
    {
      name: 'Поездка 38',
      location: 'Владивосток',
      cargo: ['Икра'],
      price: 12400,
      image: 'http://via.placeholder.com/200x300',
    },
    {
      name: 'Поездка 39',
      location: 'Якутск',
      cargo: ['Шубы', 'Алмазы'],
      price: 9500,
      image: 'http://via.placeholder.com/300x300',
    },
    {
      name: 'Поездка 40',
      location: 'Африка',
      cargo: ['Бананы', 'Дикие обезьяны'],
      price: 42400,
      image: 'http://via.placeholder.com/100x100',
    },
    {
      name: 'Поездка 41',
      location: 'Екатеринбург',
      cargo: ['Стройматериалы'],
      price: 750,
      image: 'http://via.placeholder.com/200x150',
    },
    {
      name: 'Поездка 42',
      location: 'Самара',
      cargo: ['Люди'],
      price: 1400,
      image: 'http://via.placeholder.com/300x300',
    },
    {
      name: 'Поездка 43',
      location: 'Москва',
      cargo: ['Навоз'],
      price: 3500,
      image: 'http://via.placeholder.com/300x100',
    },
    {
      name: 'Поездка 44',
      location: 'Саратов',
      cargo: ['Микротранзисторы'],
      price: 1700,
      image: 'http://via.placeholder.com/100x300',
    },
    {
      name: 'Поездка 45',
      location: 'Киров',
      cargo: ['Люди', 'Навоз'],
      price: 600,
      image: 'http://via.placeholder.com/200x200',
    },
    {
      name: 'Поездка 46',
      location: 'Вологда',
      cargo: ['Масло'],
      price: 3200,
      image: 'http://via.placeholder.com/140x80',
    },
    {
      name: 'Поездка 47',
      location: 'Питер',
      cargo: [
        'Статуэтки',
        'Картины',
        'Бухлишко',
        'Вазы',
        'Стразы',
        'Перо павлина',
      ],
      price: 3200,
      image: 'http://via.placeholder.com/140x80',
    },
    {
      name: 'Поездка 48',
      location: 'Владивосток',
      cargo: ['Икра'],
      price: 12400,
      image: 'http://via.placeholder.com/200x300',
    },
    {
      name: 'Поездка 49',
      location: 'Якутск',
      cargo: ['Шубы', 'Алмазы'],
      price: 9500,
      image: 'http://via.placeholder.com/300x300',
    },
    {
      name: 'Поездка 50',
      location: 'Африка',
      cargo: ['Бананы', 'Дикие обезьяны'],
      price: 42400,
      image: 'http://via.placeholder.com/100x100',
    },
    {
      name: 'Поездка 51',
      location: 'Екатеринбург',
      cargo: ['Стройматериалы'],
      price: 750,
      image: 'http://via.placeholder.com/200x150',
    },
    {
      name: 'Поездка 52',
      location: 'Самара',
      cargo: ['Люди'],
      price: 1400,
      image: 'http://via.placeholder.com/300x300',
    },
    {
      name: 'Поездка 53',
      location: 'Москва',
      cargo: ['Навоз'],
      price: 3500,
      image: 'http://via.placeholder.com/300x100',
    },
    {
      name: 'Поездка 54',
      location: 'Саратов',
      cargo: ['Микротранзисторы'],
      price: 1700,
      image: 'http://via.placeholder.com/100x300',
    },
    {
      name: 'Поездка 55',
      location: 'Киров',
      cargo: ['Люди', 'Навоз'],
      price: 600,
      image: 'http://via.placeholder.com/200x200',
    },
    {
      name: 'Поездка 56',
      location: 'Вологда',
      cargo: ['Масло'],
      price: 3200,
      image: 'http://via.placeholder.com/140x80',
    },
    {
      name: 'Поездка 57',
      location: 'Питер',
      cargo: [
        'Статуэтки',
        'Картины',
        'Бухлишко',
        'Вазы',
        'Стразы',
        'Перо павлина',
      ],
      price: 3200,
      image: 'http://via.placeholder.com/140x80',
    },
    {
      name: 'Поездка 58',
      location: 'Владивосток',
      cargo: ['Икра'],
      price: 12400,
      image: 'http://via.placeholder.com/200x300',
    },
    {
      name: 'Поездка 59',
      location: 'Якутск',
      cargo: ['Шубы', 'Алмазы'],
      price: 9500,
      image: 'http://via.placeholder.com/300x300',
    },
    {
      name: 'Поездка 60',
      location: 'Африка',
      cargo: ['Бананы', 'Дикие обезьяны'],
      price: 42400,
      image: 'http://via.placeholder.com/100x100',
    },
    {
      name: 'Поездка 61',
      location: 'Екатеринбург',
      cargo: ['Стройматериалы'],
      price: 750,
      image: 'http://via.placeholder.com/200x150',
    },
    {
      name: 'Поездка 62',
      location: 'Самара',
      cargo: ['Люди'],
      price: 1400,
      image: 'http://via.placeholder.com/300x300',
    },
    {
      name: 'Поездка 63',
      location: 'Москва',
      cargo: ['Навоз'],
      price: 3500,
      image: 'http://via.placeholder.com/300x100',
    },
    {
      name: 'Поездка 64',
      location: 'Саратов',
      cargo: ['Микротранзисторы'],
      price: 1700,
      image: 'http://via.placeholder.com/100x300',
    },
    {
      name: 'Поездка 65',
      location: 'Киров',
      cargo: ['Люди', 'Навоз'],
      price: 600,
      image: 'http://via.placeholder.com/200x200',
    },
    {
      name: 'Поездка 66',
      location: 'Вологда',
      cargo: ['Масло'],
      price: 3200,
      image: 'http://via.placeholder.com/140x80',
    },
    {
      name: 'Поездка 67',
      location: 'Питер',
      cargo: [
        'Статуэтки',
        'Картины',
        'Бухлишко',
        'Вазы',
        'Стразы',
        'Перо павлина',
      ],
      price: 3200,
      image: 'http://via.placeholder.com/140x80',
    },
    {
      name: 'Поездка 68',
      location: 'Владивосток',
      cargo: ['Икра'],
      price: 12400,
      image: 'http://via.placeholder.com/200x300',
    },
    {
      name: 'Поездка 69',
      location: 'Якутск',
      cargo: ['Шубы', 'Алмазы'],
      price: 9500,
      image: 'http://via.placeholder.com/300x300',
    },
    {
      name: 'Поездка 70',
      location: 'Африка',
      cargo: ['Бананы', 'Дикие обезьяны'],
      price: 42400,
      image: 'http://via.placeholder.com/100x100',
    },
    {
      name: 'Поездка 71',
      location: 'Екатеринбург',
      cargo: ['Стройматериалы'],
      price: 750,
      image: 'http://via.placeholder.com/200x150',
    },
    {
      name: 'Поездка 72',
      location: 'Самара',
      cargo: ['Люди'],
      price: 1400,
      image: 'http://via.placeholder.com/300x300',
    },
    {
      name: 'Поездка 73',
      location: 'Москва',
      cargo: ['Навоз'],
      price: 3500,
      image: 'http://via.placeholder.com/300x100',
    },
    {
      name: 'Поездка 74',
      location: 'Саратов',
      cargo: ['Микротранзисторы'],
      price: 1700,
      image: 'http://via.placeholder.com/100x300',
    },
    {
      name: 'Поездка 75',
      location: 'Киров',
      cargo: ['Люди', 'Навоз'],
      price: 600,
      image: 'http://via.placeholder.com/200x200',
    },
    {
      name: 'Поездка 76',
      location: 'Вологда',
      cargo: ['Масло'],
      price: 3200,
      image: 'http://via.placeholder.com/140x80',
    },
    {
      name: 'Поездка 77',
      location: 'Питер',
      cargo: [
        'Статуэтки',
        'Картины',
        'Бухлишко',
        'Вазы',
        'Стразы',
        'Перо павлина',
      ],
      price: 3200,
      image: 'http://via.placeholder.com/140x80',
    },
    {
      name: 'Поездка 78',
      location: 'Владивосток',
      cargo: ['Икра'],
      price: 12400,
      image: 'http://via.placeholder.com/200x300',
    },
    {
      name: 'Поездка 79',
      location: 'Якутск',
      cargo: ['Шубы', 'Алмазы'],
      price: 9500,
      image: 'http://via.placeholder.com/300x300',
    },
    {
      name: 'Поездка 80',
      location: 'Африка',
      cargo: ['Бананы', 'Дикие обезьяны'],
      price: 42400,
      image: 'http://via.placeholder.com/100x100',
    },
    {
      name: 'Поездка 81',
      location: 'Екатеринбург',
      cargo: ['Стройматериалы'],
      price: 750,
      image: 'http://via.placeholder.com/200x150',
    },
    {
      name: 'Поездка 82',
      location: 'Самара',
      cargo: ['Люди'],
      price: 1400,
      image: 'http://via.placeholder.com/300x300',
    },
    {
      name: 'Поездка 83',
      location: 'Москва',
      cargo: ['Навоз'],
      price: 3500,
      image: 'http://via.placeholder.com/300x100',
    },
    {
      name: 'Поездка 84',
      location: 'Саратов',
      cargo: ['Микротранзисторы'],
      price: 1700,
      image: 'http://via.placeholder.com/100x300',
    },
    {
      name: 'Поездка 85',
      location: 'Киров',
      cargo: ['Люди', 'Навоз'],
      price: 600,
      image: 'http://via.placeholder.com/200x200',
    },
    {
      name: 'Поездка 86',
      location: 'Вологда',
      cargo: ['Масло'],
      price: 3200,
      image: 'http://via.placeholder.com/140x80',
    },
    {
      name: 'Поездка 87',
      location: 'Питер',
      cargo: [
        'Статуэтки',
        'Картины',
        'Бухлишко',
        'Вазы',
        'Стразы',
        'Перо павлина',
      ],
      price: 3200,
      image: 'http://via.placeholder.com/140x80',
    },
    {
      name: 'Поездка 88',
      location: 'Владивосток',
      cargo: ['Икра'],
      price: 12400,
      image: 'http://via.placeholder.com/200x300',
    },
    {
      name: 'Поездка 89',
      location: 'Якутск',
      cargo: ['Шубы', 'Алмазы'],
      price: 9500,
      image: 'http://via.placeholder.com/300x300',
    },
    {
      name: 'Поездка 90',
      location: 'Африка',
      cargo: ['Бананы', 'Дикие обезьяны'],
      price: 42400,
      image: 'http://via.placeholder.com/100x100',
    },
    {
      name: 'Поездка 91',
      location: 'Екатеринбург',
      cargo: ['Стройматериалы'],
      price: 750,
      image: 'http://via.placeholder.com/200x150',
    },
    {
      name: 'Поездка 92',
      location: 'Самара',
      cargo: ['Люди'],
      price: 1400,
      image: 'http://via.placeholder.com/300x300',
    },
    {
      name: 'Поездка 93',
      location: 'Москва',
      cargo: ['Навоз'],
      price: 3500,
      image: 'http://via.placeholder.com/300x100',
    },
    {
      name: 'Поездка 94',
      location: 'Саратов',
      cargo: ['Микротранзисторы'],
      price: 1700,
      image: 'http://via.placeholder.com/100x300',
    },
    {
      name: 'Поездка 95',
      location: 'Киров',
      cargo: ['Люди', 'Навоз'],
      price: 600,
      image: 'http://via.placeholder.com/200x200',
    },
    {
      name: 'Поездка 96',
      location: 'Вологда',
      cargo: ['Масло'],
      price: 3200,
      image: 'http://via.placeholder.com/140x80',
    },
    {
      name: 'Поездка 97',
      location: 'Питер',
      cargo: [
        'Статуэтки',
        'Картины',
        'Бухлишко',
        'Вазы',
        'Стразы',
        'Перо павлина',
      ],
      price: 3200,
      image: 'http://via.placeholder.com/140x80',
    },
    {
      name: 'Поездка 98',
      location: 'Владивосток',
      cargo: ['Икра'],
      price: 12400,
      image: 'http://via.placeholder.com/200x300',
    },
    {
      name: 'Поездка 99',
      location: 'Якутск',
      cargo: ['Шубы', 'Алмазы'],
      price: 9500,
      image: 'http://via.placeholder.com/300x300',
    },
    {
      name: 'Поездка 100',
      location: 'Африка',
      cargo: ['Бананы', 'Дикие обезьяны'],
      price: 42400,
      image: 'http://via.placeholder.com/100x100',
    },
    {
      name: 'Поездка 101',
      location: 'Екатеринбург',
      cargo: ['Стройматериалы'],
      price: 750,
      image: 'http://via.placeholder.com/200x150',
    },
    {
      name: 'Поездка 102',
      location: 'Самара',
      cargo: ['Люди'],
      price: 1400,
      image: 'http://via.placeholder.com/300x300',
    },
    {
      name: 'Поездка 103',
      location: 'Якутск',
      cargo: ['Шубы', 'Алмазы'],
      price: 9500,
      image: 'http://via.placeholder.com/300x300',
    },
  ],
};

export { mockDatabase };
